"""Deterministic forbidden-content and grounding checks for PR drafts."""

from __future__ import annotations

import re
from collections.abc import Iterable
from pathlib import Path

from foreshadow.contribution.maintainer.context import MaintainerDraftContext

_CJK = re.compile(r"[\u4e00-\u9fff]")
_ISSUE_REF = re.compile(r"#(\d+)")
_EMAIL = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.IGNORECASE)
_IPV4 = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
_ABS_PATH = re.compile(
    r"(?:/Users/|/home/|/var/lib/foreshadow|/etc/foreshadow|/tmp/[A-Za-z0-9._/-]+)"
)
_SECRET = re.compile(
    r"\b(?:ghp_|gho_|ghu_|ghs_|github_pat_|sk-|xai-|AKIA)[A-Za-z0-9_-]{8,}\b"
    r"|GITHUB_TOKEN|OPENAI_API_KEY|ANTHROPIC_API_KEY|XAI_API_KEY",
    re.IGNORECASE,
)
_HYPE = re.compile(
    r"\b(?:comprehensive|robust|seamless|revolutionary|cutting-edge|enterprise-grade)\b",
    re.IGNORECASE,
)
_AI_ATTRIBUTION = re.compile(
    r"(?:generated by|generated with|written by|implemented by|authored by)\s+"
    r"(?:an?\s+)?(?:ai|llm|agent|claude|gpt|cursor|grok|openai|anthropic|mini-?swe)"
    r"|\bthe agent (?:found|implemented|wrote|generated)\b"
    r"|\bas an ai\b|\bai[- ]assisted\b|\bagent found\b|\bai implemented\b"
    r"|co-authored-by:\s*(?:cursor|grok|claude|gpt|openai|anthropic|an?\s+ai)",
    re.IGNORECASE,
)
_TECH_NAME = re.compile(
    r"\b(?:claude|cursor|grok|gpt|openai|anthropic|llm|agent|mini-?swe|ai)\b",
    re.IGNORECASE,
)
_STOP = frozenset(
    {
        "that",
        "this",
        "with",
        "from",
        "when",
        "than",
        "such",
        "into",
        "they",
        "their",
        "them",
        "then",
        "have",
        "been",
        "were",
        "will",
        "does",
        "must",
        "should",
        "could",
        "would",
        "about",
        "after",
        "before",
        "never",
        "reach",
        "only",
        "also",
        "just",
        "over",
        "under",
        "your",
        "ours",
        "what",
        "where",
        "which",
        "while",
        "there",
        "here",
        "onto",
        "same",
        "each",
        "other",
        "more",
        "most",
        "some",
        "any",
        "not",
        "and",
        "for",
        "the",
    }
)
_FILEISH = re.compile(
    r"\b[\w.-]+(?:/[\w.-]+){1,6}\.(?:go|py|ts|js|rs|md|toml|json|yml|yaml)\b"
)

# Category → patterns. A hit is a leak unless the exact span is already in
# the issue or repo guidelines (not the patch: a poisoned comment must not
# launder Official ranking notes into the PR body).
LEAK_CATEGORIES: dict[str, tuple[re.Pattern[str], ...]] = {
    "ranking": (
        re.compile(r"official\s+top\s*5", re.IGNORECASE),
        re.compile(r"\btop\s*5\b", re.IGNORECASE),
        re.compile(r"reviewer\s+score", re.IGNORECASE),
        re.compile(r"潜力"),
        re.compile(r"进入匹配"),
        re.compile(r"主审"),
    ),
    "human_confirm": (
        re.compile(r"human[- ]confirm(?:ed|ation)?", re.IGNORECASE),
        re.compile(r"人工确认"),
    ),
    "process": (
        re.compile(r"\bforeshadow\b", re.IGNORECASE),
        re.compile(r"\bentry strategy\b", re.IGNORECASE),
        re.compile(r"\bentry_revision\b", re.IGNORECASE),
        re.compile(r"\bmission(?:_|\s+)id\b", re.IGNORECASE),
        re.compile(r"\bjob(?:_|\s+)id\b", re.IGNORECASE),
        re.compile(r"\bartifact(?:_|\s+)id\b", re.IGNORECASE),
        re.compile(r"\bexecutor provenance\b", re.IGNORECASE),
        re.compile(r"openai/deepseek[^\s]*", re.IGNORECASE),
        re.compile(r"\bmini-?swe(?:-agent)?\b", re.IGNORECASE),
        re.compile(r"\b(?:local|production)\s+db\b", re.IGNORECASE),
        re.compile(r"\bworktree\b", re.IGNORECASE),
        re.compile(r"\bsandbox\b", re.IGNORECASE),
    ),
}


def _allowed_blob(ctx: MaintainerDraftContext, *, include_diff: bool = False) -> str:
    parts = [
        ctx.issue_title,
        ctx.issue_body,
        ctx.contributing,
        ctx.pr_template,
        " ".join(ctx.test_commands),
        " ".join(ctx.changed_files),
    ]
    if include_diff:
        parts.append(ctx.diff)
    return "\n".join(parts)


def looks_internal(text: str) -> bool:
    blob = text or ""
    return any(
        pat.search(blob) for patterns in LEAK_CATEGORIES.values() for pat in patterns
    )


def _already_in_sources(span: str, allowed: str) -> bool:
    if not span.strip():
        return False
    return span.lower() in allowed.lower()


def leak_hits(text: str, ctx: MaintainerDraftContext) -> list[str]:
    allowed = _allowed_blob(ctx)
    found: list[str] = []
    for category, patterns in LEAK_CATEGORIES.items():
        for pat in patterns:
            for match in pat.finditer(text):
                span = match.group(0)
                if _already_in_sources(span, allowed):
                    continue
                found.append(f"{category}:{span}")
    return found


def privacy_hits(text: str, ctx: MaintainerDraftContext) -> list[str]:
    allowed = _allowed_blob(ctx)
    found: list[str] = []
    for pat, label in (
        (_ABS_PATH, "path"),
        (_EMAIL, "email"),
        (_SECRET, "secret"),
        (_IPV4, "ip"),
    ):
        for match in pat.finditer(text):
            span = match.group(0)
            if _already_in_sources(span, allowed):
                continue
            found.append(f"{label}:{span}")
    return found


def language_hits(text: str, ctx: MaintainerDraftContext) -> list[str]:
    if ctx.language != "en":
        return []
    if _CJK.search(text):
        return ["cjk-in-english-repo"]
    return []


def hype_hits(text: str) -> list[str]:
    return [m.group(0) for m in _HYPE.finditer(text)]


def ai_attribution_hits(text: str, ctx: MaintainerDraftContext) -> list[str]:
    found = [m.group(0) for m in _AI_ATTRIBUTION.finditer(text)]
    allowed = _allowed_blob(ctx, include_diff=True)
    for match in _TECH_NAME.finditer(text):
        name = match.group(0)
        if _already_in_sources(name, allowed):
            continue
        # Bare product names are only allowed when the issue/diff is about them.
        found.append(f"ungrounded-name:{name}")
    return found


def issue_refs(text: str) -> list[int]:
    return [int(n) for n in _ISSUE_REF.findall(text)]


def cross_issue_hits(text: str, ctx: MaintainerDraftContext) -> list[str]:
    allowed_nums = set(issue_refs(ctx.issue_title + "\n" + ctx.issue_body))
    if ctx.issue_number is not None:
        allowed_nums.add(int(ctx.issue_number))
    found: list[str] = []
    for num in issue_refs(text):
        if num not in allowed_nums:
            found.append(f"#{num}")
    return found


def _tokens(text: str) -> set[str]:
    words = re.findall(r"[a-z0-9_]+", text.lower())
    return {w for w in words if len(w) >= 4 and w not in _STOP}


def _claims(body: str) -> list[str]:
    claims: list[str] = []
    for raw in body.splitlines():
        line = raw.strip()
        if not line:
            continue
        if re.match(r"^closes\s+#\d+\.?$", line, re.IGNORECASE):
            continue
        if re.match(r"^tests?:\s*`[^`]+`\s*$", line, re.IGNORECASE):
            continue
        if line.lower().startswith("tests:"):
            continue
        if line.startswith(("- ", "* ", "• ")):
            claims.append(line[2:].strip())
            continue
        claims.append(line)
    return claims


_STRUCTURAL = frozenset(
    {
        "update",
        "apply",
        "attached",
        "patch",
        "cover",
        "missing",
        "phrases",
        "regression",
        "cases",
        "treat",
        "recognize",
        "tests",
        "closes",
    }
)


def grounding_hits(body: str, ctx: MaintainerDraftContext) -> list[str]:
    allowed = _tokens(_allowed_blob(ctx, include_diff=True))
    bad: list[str] = []
    for claim in _claims(body):
        local = claim
        for path in ctx.changed_files:
            local = local.replace(path, " ")
            local = local.replace(Path(path).name, " ")
        toks = _tokens(local) - _STRUCTURAL
        if not toks:
            continue
        if len(toks & allowed) >= 2 or (
            len(toks) <= 2 and toks <= allowed | _STRUCTURAL
        ):
            continue
        if toks <= allowed:
            continue
        bad.append(claim[:160])
    return bad


def test_claim_hits(body: str, ctx: MaintainerDraftContext) -> list[str]:
    allowed = set(ctx.test_commands)
    allowed.update(re.findall(r"`((?:go test|pytest|npm test)[^`]*)`", ctx.issue_body))
    found: list[str] = []
    for match in re.finditer(r"`((?:go test|pytest|npm test)[^`]*)`", body):
        cmd = match.group(1).strip()
        if cmd not in allowed and cmd not in ctx.issue_body and cmd not in ctx.diff:
            found.append(cmd)
    return found


def diff_claim_hits(body: str, ctx: MaintainerDraftContext) -> list[str]:
    allowed = {Path(p).as_posix() for p in ctx.changed_files}
    allowed.update(Path(p).name for p in ctx.changed_files)
    found: list[str] = []
    for match in _FILEISH.finditer(body):
        path = match.group(0)
        if (
            path in allowed
            or Path(path).name in allowed
            or path in ctx.issue_body
            or path in ctx.diff
        ):
            continue
        found.append(path)
    return found


def diff_size(diff: str) -> tuple[int, int]:
    added = deleted = 0
    for line in (diff or "").splitlines():
        if line.startswith("+") and not line.startswith("+++"):
            added += 1
        elif line.startswith("-") and not line.startswith("---"):
            deleted += 1
    return added, deleted


def style_hits(title: str, body: str, ctx: MaintainerDraftContext) -> list[str]:
    found = [f"hype:{w}" for w in hype_hits(f"{title}\n{body}")]
    added, deleted = diff_size(ctx.diff)
    if added + deleted <= 12 and len(body) > 900:
        found.append("small-patch-too-long")
    if not title.strip():
        found.append("empty-title")
    return found


def default_semantic_reasons(draft: str) -> list[str]:
    reasons: list[str] = []
    if re.search(
        r"\b(?:as an ai|i implemented this|the agent)\b", draft, re.IGNORECASE
    ):
        reasons.append("agent-voice")
    reasons.extend(f"hype:{w}" for w in hype_hits(draft))
    return reasons


def iter_unique(items: Iterable[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for item in items:
        key = item.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out
